version: 2

jobs:
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  build:
    docker:
      - image: circleci/node:9-stretch-browsers

    working_directory: ~/
    steps:
      - run:
          name: Do Nothing
          command: ls -la
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  make_timelapse:
    docker:
      - image: circleci/python:3.7.3

    working_directory: ~/
    steps:
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get upgrade -y
            sudo apt-get install -y zip wget iputils-ping curl jq build-essential libssl-dev python python-pip python3 python3-pip file libgcrypt-dev git sudo build-essential libssl-dev awscli vim ffmpeg sqlite3
            pip3 install awscli --upgrade --user
      - run:
          name: Make Timelapse
          command: |
            git clone https://$GITHUB_TOKEN@github.com/mathew-fleisch/timelapse-pipeline.git
            cd timelapse-pipeline
            TARGET_DIR=$(pwd)
            mkdir -p files
            cd scripts/processor
            if ! [ -f "start.sh" ]; then
              echo "Missing start.sh script"
              exit 1
            fi
            echo "Make Timelapse..."
            echo "TARGET_DATE=$TARGET_DATE"
            echo "SOURCE_NAME=$SOURCE_NAME"
            echo "SOURCE_BASE=$SOURCE_BASE"
            ./start.sh --name ${SOURCE_NAME} --target-date ${TARGET_DATE} --source-base ${SOURCE_BASE} --target-dir ${TARGET_DIR}/files --remove-night 1 --target-base ss3://eaze-timelapse/pipeline --sqlite-db timelapse.db



# WORKFLOW - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
workflows:
  version: 2
  ad-hoc-build-processes:
    jobs:
      - build:
          filters:
            branches:
              only: never-build-this-automatically
      - make_timelapse:
          context: timelapse
          filters:
            branches:
              only: never-build-this-automatically
